### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by brunoherrera** [KevCui/opensubtitles-dl#1]
`ubuntu@DESKTOP-794QV8P:/mnt/d/GITHUB/FOREIGN/opensubtitles-dl$ ./opensubtitles-dl.sh -n 'the witcher s02e01' -l spa
./opensubtitles-dl.sh: line 16: $'\r': command not found
: invalid optiondl.sh: line 17: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
: invalid optiondl.sh: line 18: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./opensubtitles-dl.sh: line 19: $'\r': command not found
./opensubtitles-dl.sh: line 20: syntax error near unexpected token `$'{\r''
'/opensubtitles-dl.sh: line 20: `usage() {`

all dependencies are installed

**Comment by KevCui** [comment]
Hey @brunoherrera, could you please run `bash -x ./opensubtitles-dl.sh -n 'the witcher s02e01' -l spa` to capture debug logs and share them here? I need debug logs to investigate your issue. Thanks!

**Comment by KevCui** [comment]
The current logs are strange. It shows ` $'\r': command not found` . It looks like the script is edited on other platform, maybe try  `dos2unix` helps. Regarding `invalid optiondl.sh`, no idea what's that.

**Comment by brunoherrera** [comment]
> maybe try `dos2unix`

that did the trick :) I was getting the same output with bash -x, thanks!!
